// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** KiCad: C2943844:SOD-123FL_L2.7-W1.8-LS3.7-RD */
export const SOD_123FL_L2_7_W1_8_LS3_7_RD: Footprint = { id: "C2943844:SOD-123FL_L2.7-W1.8-LS3.7-RD", file: fileURLToPath(new URL("./SOD-123FL_L2.7-W1.8-LS3.7-RD.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["1","2"],"mounting":"smd"} }
