// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * SMF16A_C2943844
 *
 * KiCad symbol: `C2943844:SMF16A_C2943844`. Reference prefix: `U`.
 * @see https://www.lcsc.com/datasheet/C2943844.pdf
 * Keywords: TVS.
 * Default footprint: C2943844:SOD-123FL_L2.7-W1.8-LS3.7-RD.
 */
export class SMF16A_C2943844 extends Component.withPins({
  "C": "1",
  "A": "2",
}) {
  override symbolSource = fileURLToPath(new URL("./C2943844.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { C: "unspecified", A: "unspecified", ...opts.pinTypes } });
  }
  override schema = "C2943844:SMF16A_C2943844";
  override referencePrefix = "U";
}
