// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** KiCad: C461018:SOT-23-3_L2.9-W1.3-P1.90-LS2.4-BR */
export const SOT_23_3_L2_9_W1_3_P1_90_LS2_4_BR: Footprint = { id: "C461018:SOT-23-3_L2.9-W1.3-P1.90-LS2.4-BR", file: fileURLToPath(new URL("./SOT-23-3_L2.9-W1.3-P1.90-LS2.4-BR.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["1","2","3"],"mounting":"smd"} }
