// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * DMN3200U-7
 *
 * KiCad symbol: `C461018:DMN3200U-7`. Reference prefix: `Q`.
 * @see https://lcsc.com/product-detail/Transistors-NPN-PNP_Diodes-Incorporated-DMN3200U-7_C461018.html
 * Keywords: MOSFETs.
 * Default footprint: C461018:SOT-23-3_L2.9-W1.3-P1.90-LS2.4-BR.
 */
export class DMN3200U_7 extends Component.withPins({
  "S": "2",
  "G": "1",
  "D": "3",
}) {
  override symbolSource = fileURLToPath(new URL("./C461018.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { S: "unspecified", G: "input", D: "unspecified", ...opts.pinTypes } });
  }
  override schema = "C461018:DMN3200U-7";
  override referencePrefix = "Q";
}
