// Generated from native KiCad footprints.
import type { Footprint } from '../../src/footprint'

/** 'Piranha' RGB LED, through hole, common anode, 7.62x7.62mm, BGRA pin order, https://cdn-shop.adafruit.com/datasheets/BL-FL7680RGB.pdf
 * KiCad: LED_THT:LED_BL-FL7680RGB
 * Keywords: RGB LED Piranha Super-Flux BetLux */
export const LED_BL_FL7680RGB: Footprint = { id: "LED_THT:LED_BL-FL7680RGB", ...{"pads":["1","2","3","4"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 1.27mm, z-position of LED center 1.6mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O1.27mm_Z1.6mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O1_27mm_Z1_6mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O1.27mm_Z1.6mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 1.27mm, z-position of LED center 4.9mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O1.27mm_Z4.9mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O1_27mm_Z4_9mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O1.27mm_Z4.9mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 1.27mm, z-position of LED center 8.2mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O1.27mm_Z8.2mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O1_27mm_Z8_2mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O1.27mm_Z8.2mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 3.81mm, z-position of LED center 1.6mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O3.81mm_Z1.6mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O3_81mm_Z1_6mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O3.81mm_Z1.6mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 3.81mm, z-position of LED center 4.9mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O3.81mm_Z4.9mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O3_81mm_Z4_9mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O3.81mm_Z4.9mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 3.81mm, z-position of LED center 8.2mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O3.81mm_Z8.2mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O3_81mm_Z8_2mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O3.81mm_Z8.2mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 6.35mm, z-position of LED center 1.6mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O6.35mm_Z1.6mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O6_35mm_Z1_6mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O6.35mm_Z1.6mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 6.35mm, z-position of LED center 4.9mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O6.35mm_Z4.9mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O6_35mm_Z4_9mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O6.35mm_Z4.9mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 1.8mm, size 1.8x2.4mm, horizontal offset 6.35mm, z-position of LED center 8.2mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O6.35mm_Z8.2mm
 * Keywords: LED */
export const LED_D1_8mm_W1_8mm_H2_4mm_Horizontal_O6_35mm_Z8_2mm: Footprint = { id: "LED_THT:LED_D1.8mm_W1.8mm_H2.4mm_Horizontal_O6.35mm_Z8.2mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Round, Rectangular, size 3.3x2.4mm, diameter 1.8mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D1.8mm_W3.3mm_H2.4mm
 * Keywords: LED */
export const LED_D1_8mm_W3_3mm_H2_4mm: Footprint = { id: "LED_THT:LED_D1.8mm_W3.3mm_H2.4mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 10.0mm, 3 pins, http://www.kingbright.com/attachments/file/psearch/000/00/20131112/L-819EGW(Ver.13A).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D10.0mm-3
 * Keywords: LED */
export const LED_D10_0mm_3: Footprint = { id: "LED_THT:LED_D10.0mm-3", ...{"pads":["1","2","3"],"mounting":"through_hole"} }

/** LED, diameter 10.0mm, 2 pins, http://cdn-reichelt.de/documents/datenblatt/A500/LED10-4500RT%23KIN.pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D10.0mm
 * Keywords: LED */
export const LED_D10_0mm: Footprint = { id: "LED_THT:LED_D10.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Round, Flat Top, Rectangular, size 4.0x2.8mm, diameter 2.0mm, 2 pins, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-1034IDT(Ver.14A).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D2.0mm_W4.0mm_H2.8mm_FlatTop
 * Keywords: LED */
export const LED_D2_0mm_W4_0mm_H2_8mm_FlatTop: Footprint = { id: "LED_THT:LED_D2.0mm_W4.0mm_H2.8mm_FlatTop", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Round, Flat Top, Rectangular, size 4.8x2.5mm, diameter 2.0mm, 2 pins, http://www.kingbright.com/attachments/file/psearch/000/00/20160808bak/L-13GD(Ver.9B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D2.0mm_W4.8mm_H2.5mm_FlatTop
 * Keywords: LED */
export const LED_D2_0mm_W4_8mm_H2_5mm_FlatTop: Footprint = { id: "LED_THT:LED_D2.0mm_W4.8mm_H2.5mm_FlatTop", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 20.0mm, 2 pins, http://cdn-reichelt.de/documents/datenblatt/A500/DLC2-6GD%28V6%29.pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D20.0mm
 * Keywords: LED */
export const LED_D20_0mm: Footprint = { id: "LED_THT:LED_D20.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, 3 pins, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-3VSURKCGKC(Ver.12A).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm-3
 * Keywords: LED */
export const LED_D3_0mm_3: Footprint = { id: "LED_THT:LED_D3.0mm-3", ...{"pads":["1","2","3"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm
 * Keywords: LED */
export const LED_D3_0mm: Footprint = { id: "LED_THT:LED_D3.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, 2 pins, clear, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Clear
 * Keywords: LED */
export const LED_D3_0mm_Clear: Footprint = { id: "LED_THT:LED_D3.0mm_Clear", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Round, Flat Top, diameter 3.0mm, 2 pins, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-47XEC(Ver.14A).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_FlatTop
 * Keywords: LED */
export const LED_D3_0mm_FlatTop: Footprint = { id: "LED_THT:LED_D3.0mm_FlatTop", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 1.27mm, z-position of LED center 10.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z10.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O1_27mm_Z10_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z10.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 1.27mm, z-position of LED center 2.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z2.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O1_27mm_Z2_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z2.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 1.27mm, z-position of LED center 2.0mm, 2 pins, clear, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z2.0mm_Clear
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O1_27mm_Z2_0mm_Clear: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z2.0mm_Clear", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 1.27mm, z-position of LED center 2.0mm, 2 pins, infrared, black, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z2.0mm_IRBlack
 * Keywords: LED IR */
export const LED_D3_0mm_Horizontal_O1_27mm_Z2_0mm_IRBlack: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z2.0mm_IRBlack", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 1.27mm, z-position of LED center 2.0mm, 2 pins, infrared, grey, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z2.0mm_IRGrey
 * Keywords: LED IR */
export const LED_D3_0mm_Horizontal_O1_27mm_Z2_0mm_IRGrey: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z2.0mm_IRGrey", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 1.27mm, z-position of LED center 6.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z6.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O1_27mm_Z6_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O1.27mm_Z6.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 3.81mm, z-position of LED center 10.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O3.81mm_Z10.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O3_81mm_Z10_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O3.81mm_Z10.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 3.81mm, z-position of LED center 2.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O3.81mm_Z2.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O3_81mm_Z2_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O3.81mm_Z2.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 3.81mm, z-position of LED center 6.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O3.81mm_Z6.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O3_81mm_Z6_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O3.81mm_Z6.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 6.35mm, z-position of LED center 10.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O6.35mm_Z10.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O6_35mm_Z10_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O6.35mm_Z10.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 6.35mm, z-position of LED center 2.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O6.35mm_Z2.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O6_35mm_Z2_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O6.35mm_Z2.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, horizontal offset 6.35mm, z-position of LED center 6.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_Horizontal_O6.35mm_Z6.0mm
 * Keywords: LED */
export const LED_D3_0mm_Horizontal_O6_35mm_Z6_0mm: Footprint = { id: "LED_THT:LED_D3.0mm_Horizontal_O6.35mm_Z6.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, 2 pins, infrared, black, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_IRBlack
 * Keywords: LED IR */
export const LED_D3_0mm_IRBlack: Footprint = { id: "LED_THT:LED_D3.0mm_IRBlack", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 3.0mm, 2 pins, infrared, grey, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D3.0mm_IRGrey
 * Keywords: LED IR */
export const LED_D3_0mm_IRGrey: Footprint = { id: "LED_THT:LED_D3.0mm_IRGrey", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 4.0mm, 2 pins, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-43GD(Ver.17B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D4.0mm
 * Keywords: LED */
export const LED_D4_0mm: Footprint = { id: "LED_THT:LED_D4.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, 3 pins, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-59EGC(Ver.20A).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm-3
 * Keywords: LED */
export const LED_D5_0mm_3: Footprint = { id: "LED_THT:LED_D5.0mm-3", ...{"pads":["1","2","3"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 3.81mm, z-position of LED center 3.0mm, 3 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm-3_Horizontal_O3.81mm_Z3.0mm
 * Keywords: LED */
export const LED_D5_0mm_3_Horizontal_O3_81mm_Z3_0mm: Footprint = { id: "LED_THT:LED_D5.0mm-3_Horizontal_O3.81mm_Z3.0mm", ...{"pads":["1","2","3"],"mounting":"through_hole"} }

/** LED, RGB, diameter 5.0mm, 4 pins, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-154A4SUREQBFZGEW(Ver.13A).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm-4_RGB
 * Keywords: LED */
export const LED_D5_0mm_4_RGB: Footprint = { id: "LED_THT:LED_D5.0mm-4_RGB", ...{"pads":["1","2","3","4"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, 4 pins, WP154A4, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-154A4SUREQBFZGEW(Ver.11A).pdf
 * KiCad: LED_THT:LED_D5.0mm-4_RGB_Staggered_Pins
 * Keywords: rgb led */
export const LED_D5_0mm_4_RGB_Staggered_Pins: Footprint = { id: "LED_THT:LED_D5.0mm-4_RGB_Staggered_Pins", ...{"pads":["1","2","3","4"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, 4 pins, WP154A4, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-154A4SUREQBFZGEW(Ver.11A).pdf
 * KiCad: LED_THT:LED_D5.0mm-4_RGB_Wide_Pins
 * Keywords: LED diameter 5.0mm 2 pins diameter 5.0mm 3 pins diameter 5.0mm 4 pins RGB RGBLED */
export const LED_D5_0mm_4_RGB_Wide_Pins: Footprint = { id: "LED_THT:LED_D5.0mm-4_RGB_Wide_Pins", ...{"pads":["1","2","3","4"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, 2 pins, http://cdn-reichelt.de/documents/datenblatt/A500/LL-504BC2E-009.pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm
 * Keywords: LED */
export const LED_D5_0mm: Footprint = { id: "LED_THT:LED_D5.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, 2 pins, clear, http://cdn-reichelt.de/documents/datenblatt/A500/LL-504BC2E-009.pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Clear
 * Keywords: LED */
export const LED_D5_0mm_Clear: Footprint = { id: "LED_THT:LED_D5.0mm_Clear", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Round, Flat Top, diameter 5.0mm, 2 pins, https://www.kingbright.com/attachments/file/psearch/000/00/watermark00/L-483GDT(Ver.12B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_FlatTop
 * Keywords: LED */
export const LED_D5_0mm_FlatTop: Footprint = { id: "LED_THT:LED_D5.0mm_FlatTop", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 1.27mm, z-position of LED center 15.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z15.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O1_27mm_Z15_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z15.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 1.27mm, z-position of LED center 3.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z3.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O1_27mm_Z3_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z3.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 1.27mm, z-position of LED center 3.0mm, 2 pins, clear, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z3.0mm_Clear
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O1_27mm_Z3_0mm_Clear: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z3.0mm_Clear", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 1.27mm, z-position of LED center 3.0mm, 2 pins, infrared, black, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z3.0mm_IRBlack
 * Keywords: LED IR */
export const LED_D5_0mm_Horizontal_O1_27mm_Z3_0mm_IRBlack: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z3.0mm_IRBlack", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 1.27mm, z-position of LED center 3.0mm, 2 pins, infrared, grey, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z3.0mm_IRGrey
 * Keywords: LED IR */
export const LED_D5_0mm_Horizontal_O1_27mm_Z3_0mm_IRGrey: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z3.0mm_IRGrey", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 1.27mm, z-position of LED center 9.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z9.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O1_27mm_Z9_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O1.27mm_Z9.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 3.81mm, z-position of LED center 15.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O3.81mm_Z15.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O3_81mm_Z15_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O3.81mm_Z15.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 3.81mm, z-position of LED center 3.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O3.81mm_Z3.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O3_81mm_Z3_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O3.81mm_Z3.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 3.81mm, z-position of LED center 9.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O3.81mm_Z9.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O3_81mm_Z9_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O3.81mm_Z9.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 6.35mm, z-position of LED center 15.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O6.35mm_Z15.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O6_35mm_Z15_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O6.35mm_Z15.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 6.35mm, z-position of LED center 3.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O6.35mm_Z3.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O6_35mm_Z3_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O6.35mm_Z3.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, horizontal offset 6.35mm, z-position of LED center 9.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_Horizontal_O6.35mm_Z9.0mm
 * Keywords: LED */
export const LED_D5_0mm_Horizontal_O6_35mm_Z9_0mm: Footprint = { id: "LED_THT:LED_D5.0mm_Horizontal_O6.35mm_Z9.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, 2 pins, infrared, black, http://cdn-reichelt.de/documents/datenblatt/A500/LL-504BC2E-009.pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_IRBlack
 * Keywords: LED IR */
export const LED_D5_0mm_IRBlack: Footprint = { id: "LED_THT:LED_D5.0mm_IRBlack", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 5.0mm, 2 pins, infrared, grey, http://cdn-reichelt.de/documents/datenblatt/A500/LL-504BC2E-009.pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D5.0mm_IRGrey
 * Keywords: LED IR */
export const LED_D5_0mm_IRGrey: Footprint = { id: "LED_THT:LED_D5.0mm_IRGrey", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, diameter 8.0mm, 3 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D8.0mm-3
 * Keywords: LED */
export const LED_D8_0mm_3: Footprint = { id: "LED_THT:LED_D8.0mm-3", ...{"pads":["1","2","3"],"mounting":"through_hole"} }

/** LED, diameter 8.0mm, 2 pins, http://cdn-reichelt.de/documents/datenblatt/A500/LED8MMGE_LED8MMGN_LED8MMRT%23KIN.pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_D8.0mm
 * Keywords: LED */
export const LED_D8_0mm: Footprint = { id: "LED_THT:LED_D8.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Oval, size 5.2x3.8mm, 2 pins, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-5603QBC-D(Ver.17B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Oval_W5.2mm_H3.8mm
 * Keywords: LED */
export const LED_Oval_W5_2mm_H3_8mm: Footprint = { id: "LED_THT:LED_Oval_W5.2mm_H3.8mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 3.0x2.0mm, 2 pins, http://www.kingbright.com/attachments/file/psearch/000/00/20160808bak/L-169XCGDK(Ver.8B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W3.0mm_H2.0mm
 * Keywords: LED */
export const LED_Rectangular_W3_0mm_H2_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W3.0mm_H2.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 3.9x1.8mm, 2 pins, http://www.kingbright.com/attachments/file/psearch/000/00/20160808bak/L-2774GD(Ver.7B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W3.9mm_H1.8mm
 * Keywords: LED */
export const LED_Rectangular_W3_9mm_H1_8mm: Footprint = { id: "LED_THT:LED_Rectangular_W3.9mm_H1.8mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 3.9x1.9mm, 2 pins, https://www.kingbright.com/attachments/file/psearch/000/00/watermark00/L-144GDT(Ver.11B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W3.9mm_H1.9mm
 * Keywords: LED */
export const LED_Rectangular_W3_9mm_H1_9mm: Footprint = { id: "LED_THT:LED_Rectangular_W3.9mm_H1.9mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, 3 pins, http://www.kingbright.com/attachments/file/psearch/000/00/20160808bak/L-169XCGDK(Ver.8B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm-3Pins
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_3Pins: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm-3Pins", ...{"pads":["1","2","3"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, 2 pins, http://www.kingbright.com/attachments/file/psearch/000/00/00/L-169XCGDK(Ver.9B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 1.27mm, z-position of LED center 1.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O1.27mm_Z1.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O1_27mm_Z1_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O1.27mm_Z1.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 1.27mm, z-position of LED center 3.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O1.27mm_Z3.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O1_27mm_Z3_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O1.27mm_Z3.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 1.27mm, z-position of LED center 5.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O1.27mm_Z5.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O1_27mm_Z5_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O1.27mm_Z5.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 3.81mm, z-position of LED center 1.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O3.81mm_Z1.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O3_81mm_Z1_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O3.81mm_Z1.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 3.81mm, z-position of LED center 3.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O3.81mm_Z3.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O3_81mm_Z3_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O3.81mm_Z3.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 3.81mm, z-position of LED center 5.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O3.81mm_Z5.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O3_81mm_Z5_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O3.81mm_Z5.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 6.35mm, z-position of LED center 1.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O6.35mm_Z1.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O6_35mm_Z1_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O6.35mm_Z1.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 6.35mm, z-position of LED center 3.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O6.35mm_Z3.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O6_35mm_Z3_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O6.35mm_Z3.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x2.0mm, horizontal offset 6.35mm, z-position of LED center 5.0mm, 2 pins, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O6.35mm_Z5.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H2_0mm_Horizontal_O6_35mm_Z5_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H2.0mm_Horizontal_O6.35mm_Z5.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Rectangular, size 5.0x5.0mm, 2 pins, http://www.kingbright.com/attachments/file/psearch/000/00/20160808bak/L-169XCGDK(Ver.8B).pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_Rectangular_W5.0mm_H5.0mm
 * Keywords: LED */
export const LED_Rectangular_W5_0mm_H5_0mm: Footprint = { id: "LED_THT:LED_Rectangular_W5.0mm_H5.0mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** Datasheet can be found at https://www.gme.cz/data/attachments/dsh.511-795.1.pdf
 * KiCad: LED_THT:LED_Rectangular_W7.62mm_H4.55mm_P5.08mm_R3
 * Keywords: LED automotive super flux 7.62mm */
export const LED_Rectangular_W7_62mm_H4_55mm_P5_08mm_R3: Footprint = { id: "LED_THT:LED_Rectangular_W7.62mm_H4.55mm_P5.08mm_R3", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** LED, Side Emitter, Rectangular, size 4.5x1.6mm, 2 pins, http://cdn-reichelt.de/documents/datenblatt/A500/LED15MMGE_LED15MMGN%23KIN.pdf, generated by kicad-footprint-generator
 * KiCad: LED_THT:LED_SideEmitter_Rectangular_W4.5mm_H1.6mm
 * Keywords: LED */
export const LED_SideEmitter_Rectangular_W4_5mm_H1_6mm: Footprint = { id: "LED_THT:LED_SideEmitter_Rectangular_W4.5mm_H1.6mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** Red 5381 Series LED VCCLite https://vcclite.com/wp-content/uploads/wpallimport/files/files/5381Series.pdf http://static.vcclite.com/pdf/Mounting%20Hole%20Pattern%202.pdf
 * KiCad: LED_THT:LED_VCCLite_5381H1_6.35x6.35mm
 * Keywords: Red 5381 Series LED */
export const LED_VCCLite_5381H1_6_35x6_35mm: Footprint = { id: "LED_THT:LED_VCCLite_5381H1_6.35x6.35mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** Amber 5381 Series LED VCCLite https://vcclite.com/wp-content/uploads/wpallimport/files/files/5381Series.pdf http://static.vcclite.com/pdf/Mounting%20Hole%20Pattern%202.pdf
 * KiCad: LED_THT:LED_VCCLite_5381H3_6.35x6.35mm
 * Keywords: Amber 5381 Series LED */
export const LED_VCCLite_5381H3_6_35x6_35mm: Footprint = { id: "LED_THT:LED_VCCLite_5381H3_6.35x6.35mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** Green 5381 Series LED VCCLite https://vcclite.com/wp-content/uploads/wpallimport/files/files/5381Series.pdf http://static.vcclite.com/pdf/Mounting%20Hole%20Pattern%202.pdf
 * KiCad: LED_THT:LED_VCCLite_5381H5_6.35x6.35mm
 * Keywords: Green 5381 Series LED */
export const LED_VCCLite_5381H5_6_35x6_35mm: Footprint = { id: "LED_THT:LED_VCCLite_5381H5_6.35x6.35mm", ...{"pads":["1","2"],"mounting":"through_hole"} }

/** Yellow 5381 Series LED VCCLite https://vcclite.com/wp-content/uploads/wpallimport/files/files/5381Series.pdf http://static.vcclite.com/pdf/Mounting%20Hole%20Pattern%202.pdf
 * KiCad: LED_THT:LED_VCCLite_5381H7_6.35x6.35mm
 * Keywords: Yellow 5381 Series LED */
export const LED_VCCLite_5381H7_6_35x6_35mm: Footprint = { id: "LED_THT:LED_VCCLite_5381H7_6.35x6.35mm", ...{"pads":["1","2"],"mounting":"through_hole"} }
