// Generated from native KiCad footprints.
import type { Footprint } from '../../src/footprint'

/** Mounting Hole 2.1mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.1mm
 * Keywords: mountinghole */
export const MountingHole_2_1mm: Footprint = { id: "MountingHole:MountingHole_2.1mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.2mm, M2, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2
 * Keywords: mountinghole M2 */
export const MountingHole_2_2mm_M2: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.2mm, M2, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_DIN965
 * Keywords: mountinghole M2 DIN965 */
export const MountingHole_2_2mm_M2_DIN965: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_DIN965", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_DIN965_Pad
 * Keywords: mountinghole M2 DIN965 */
export const MountingHole_2_2mm_M2_DIN965_Pad: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_DIN965_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_DIN965_Pad_TopBottom
 * Keywords: mountinghole M2 DIN965 */
export const MountingHole_2_2mm_M2_DIN965_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_DIN965_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_DIN965_Pad_TopOnly
 * Keywords: mountinghole M2 DIN965 */
export const MountingHole_2_2mm_M2_DIN965_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_DIN965_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_ISO14580
 * Keywords: mountinghole M2 ISO14580 */
export const MountingHole_2_2mm_M2_ISO14580: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_ISO14580", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_ISO14580_Pad
 * Keywords: mountinghole M2 ISO14580 */
export const MountingHole_2_2mm_M2_ISO14580_Pad: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_ISO14580_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_ISO14580_Pad_TopBottom
 * Keywords: mountinghole M2 ISO14580 */
export const MountingHole_2_2mm_M2_ISO14580_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_ISO14580_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_ISO14580_Pad_TopOnly
 * Keywords: mountinghole M2 ISO14580 */
export const MountingHole_2_2mm_M2_ISO14580_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_ISO14580_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_ISO7380
 * Keywords: mountinghole M2 ISO7380 */
export const MountingHole_2_2mm_M2_ISO7380: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_ISO7380", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_ISO7380_Pad
 * Keywords: mountinghole M2 ISO7380 */
export const MountingHole_2_2mm_M2_ISO7380_Pad: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_ISO7380_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_ISO7380_Pad_TopBottom
 * Keywords: mountinghole M2 ISO7380 */
export const MountingHole_2_2mm_M2_ISO7380_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_ISO7380_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_ISO7380_Pad_TopOnly
 * Keywords: mountinghole M2 ISO7380 */
export const MountingHole_2_2mm_M2_ISO7380_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_ISO7380_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_Pad
 * Keywords: mountinghole M2 */
export const MountingHole_2_2mm_M2_Pad: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_Pad_TopBottom
 * Keywords: mountinghole M2 */
export const MountingHole_2_2mm_M2_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_Pad_TopOnly
 * Keywords: mountinghole M2 */
export const MountingHole_2_2mm_M2_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.2mm_M2_Pad_Via
 * Keywords: mountinghole M2 */
export const MountingHole_2_2mm_M2_Pad_Via: Footprint = { id: "MountingHole:MountingHole_2.2mm_M2_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.5mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.5mm
 * Keywords: mountinghole */
export const MountingHole_2_5mm: Footprint = { id: "MountingHole:MountingHole_2.5mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.5mm_Pad
 * Keywords: mountinghole */
export const MountingHole_2_5mm_Pad: Footprint = { id: "MountingHole:MountingHole_2.5mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.5mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_2_5mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.5mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.5mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_2_5mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.5mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.5mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_2_5mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_2.5mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm
 * Keywords: mountinghole */
export const MountingHole_2_7mm: Footprint = { id: "MountingHole:MountingHole_2.7mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.7mm, M2.5, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5
 * Keywords: mountinghole M2.5 */
export const MountingHole_2_7mm_M2_5: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.7mm, M2.5, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_DIN965
 * Keywords: mountinghole M2.5 DIN965 */
export const MountingHole_2_7mm_M2_5_DIN965: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_DIN965", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_DIN965_Pad
 * Keywords: mountinghole M2.5 DIN965 */
export const MountingHole_2_7mm_M2_5_DIN965_Pad: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_DIN965_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_DIN965_Pad_TopBottom
 * Keywords: mountinghole M2.5 DIN965 */
export const MountingHole_2_7mm_M2_5_DIN965_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_DIN965_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_DIN965_Pad_TopOnly
 * Keywords: mountinghole M2.5 DIN965 */
export const MountingHole_2_7mm_M2_5_DIN965_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_DIN965_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_ISO14580
 * Keywords: mountinghole M2.5 ISO14580 */
export const MountingHole_2_7mm_M2_5_ISO14580: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_ISO14580", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_ISO14580_Pad
 * Keywords: mountinghole M2.5 ISO14580 */
export const MountingHole_2_7mm_M2_5_ISO14580_Pad: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_ISO14580_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_ISO14580_Pad_TopBottom
 * Keywords: mountinghole M2.5 ISO14580 */
export const MountingHole_2_7mm_M2_5_ISO14580_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_ISO14580_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_ISO14580_Pad_TopOnly
 * Keywords: mountinghole M2.5 ISO14580 */
export const MountingHole_2_7mm_M2_5_ISO14580_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_ISO14580_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_ISO7380
 * Keywords: mountinghole M2.5 ISO7380 */
export const MountingHole_2_7mm_M2_5_ISO7380: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_ISO7380", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_ISO7380_Pad
 * Keywords: mountinghole M2.5 ISO7380 */
export const MountingHole_2_7mm_M2_5_ISO7380_Pad: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_ISO7380_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_ISO7380_Pad_TopBottom
 * Keywords: mountinghole M2.5 ISO7380 */
export const MountingHole_2_7mm_M2_5_ISO7380_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_ISO7380_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_ISO7380_Pad_TopOnly
 * Keywords: mountinghole M2.5 ISO7380 */
export const MountingHole_2_7mm_M2_5_ISO7380_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_ISO7380_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_Pad
 * Keywords: mountinghole M2.5 */
export const MountingHole_2_7mm_M2_5_Pad: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_Pad_TopBottom
 * Keywords: mountinghole M2.5 */
export const MountingHole_2_7mm_M2_5_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_Pad_TopOnly
 * Keywords: mountinghole M2.5 */
export const MountingHole_2_7mm_M2_5_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, M2.5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_M2.5_Pad_Via
 * Keywords: mountinghole M2.5 */
export const MountingHole_2_7mm_M2_5_Pad_Via: Footprint = { id: "MountingHole:MountingHole_2.7mm_M2.5_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_Pad
 * Keywords: mountinghole */
export const MountingHole_2_7mm_Pad: Footprint = { id: "MountingHole:MountingHole_2.7mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_2_7mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_2.7mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_2_7mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_2.7mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2.7mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2.7mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_2_7mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_2.7mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 2mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_2mm
 * Keywords: mountinghole */
export const MountingHole_2mm: Footprint = { id: "MountingHole:MountingHole_2mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 3.2mm, M3, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3
 * Keywords: mountinghole M3 */
export const MountingHole_3_2mm_M3: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 3.2mm, M3, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_DIN965
 * Keywords: mountinghole M3 DIN965 */
export const MountingHole_3_2mm_M3_DIN965: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_DIN965", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_DIN965_Pad
 * Keywords: mountinghole M3 DIN965 */
export const MountingHole_3_2mm_M3_DIN965_Pad: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_DIN965_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_DIN965_Pad_TopBottom
 * Keywords: mountinghole M3 DIN965 */
export const MountingHole_3_2mm_M3_DIN965_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_DIN965_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_DIN965_Pad_TopOnly
 * Keywords: mountinghole M3 DIN965 */
export const MountingHole_3_2mm_M3_DIN965_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_DIN965_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_ISO14580
 * Keywords: mountinghole M3 ISO14580 */
export const MountingHole_3_2mm_M3_ISO14580: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_ISO14580", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_ISO14580_Pad
 * Keywords: mountinghole M3 ISO14580 */
export const MountingHole_3_2mm_M3_ISO14580_Pad: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_ISO14580_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_ISO14580_Pad_TopBottom
 * Keywords: mountinghole M3 ISO14580 */
export const MountingHole_3_2mm_M3_ISO14580_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_ISO14580_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_ISO14580_Pad_TopOnly
 * Keywords: mountinghole M3 ISO14580 */
export const MountingHole_3_2mm_M3_ISO14580_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_ISO14580_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_ISO7380
 * Keywords: mountinghole M3 ISO7380 */
export const MountingHole_3_2mm_M3_ISO7380: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_ISO7380", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_ISO7380_Pad
 * Keywords: mountinghole M3 ISO7380 */
export const MountingHole_3_2mm_M3_ISO7380_Pad: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_ISO7380_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_ISO7380_Pad_TopBottom
 * Keywords: mountinghole M3 ISO7380 */
export const MountingHole_3_2mm_M3_ISO7380_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_ISO7380_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_ISO7380_Pad_TopOnly
 * Keywords: mountinghole M3 ISO7380 */
export const MountingHole_3_2mm_M3_ISO7380_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_ISO7380_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_Pad
 * Keywords: mountinghole M3 */
export const MountingHole_3_2mm_M3_Pad: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_Pad_TopBottom
 * Keywords: mountinghole M3 */
export const MountingHole_3_2mm_M3_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_Pad_TopOnly
 * Keywords: mountinghole M3 */
export const MountingHole_3_2mm_M3_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.2mm, M3, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.2mm_M3_Pad_Via
 * Keywords: mountinghole M3 */
export const MountingHole_3_2mm_M3_Pad_Via: Footprint = { id: "MountingHole:MountingHole_3.2mm_M3_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.5mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.5mm
 * Keywords: mountinghole */
export const MountingHole_3_5mm: Footprint = { id: "MountingHole:MountingHole_3.5mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 3.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.5mm_Pad
 * Keywords: mountinghole */
export const MountingHole_3_5mm_Pad: Footprint = { id: "MountingHole:MountingHole_3.5mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.5mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_3_5mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_3.5mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.5mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_3_5mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_3.5mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.5mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_3_5mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_3.5mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.7mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.7mm
 * Keywords: mountinghole */
export const MountingHole_3_7mm: Footprint = { id: "MountingHole:MountingHole_3.7mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 3.7mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.7mm_Pad
 * Keywords: mountinghole */
export const MountingHole_3_7mm_Pad: Footprint = { id: "MountingHole:MountingHole_3.7mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.7mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.7mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_3_7mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_3.7mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.7mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.7mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_3_7mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_3.7mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3.7mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3.7mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_3_7mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_3.7mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3mm
 * Keywords: mountinghole */
export const MountingHole_3mm: Footprint = { id: "MountingHole:MountingHole_3mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 3mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3mm_Pad
 * Keywords: mountinghole */
export const MountingHole_3mm_Pad: Footprint = { id: "MountingHole:MountingHole_3mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_3mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_3mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_3mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_3mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 3mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_3mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_3mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_3mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4
 * Keywords: mountinghole M4 */
export const MountingHole_4_3mm_M4: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 4.3mm, M4, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_DIN965
 * Keywords: mountinghole M4 DIN965 */
export const MountingHole_4_3mm_M4_DIN965: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_DIN965", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_DIN965_Pad
 * Keywords: mountinghole M4 DIN965 */
export const MountingHole_4_3mm_M4_DIN965_Pad: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_DIN965_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_DIN965_Pad_TopBottom
 * Keywords: mountinghole M4 DIN965 */
export const MountingHole_4_3mm_M4_DIN965_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_DIN965_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_DIN965_Pad_TopOnly
 * Keywords: mountinghole M4 DIN965 */
export const MountingHole_4_3mm_M4_DIN965_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_DIN965_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_ISO14580
 * Keywords: mountinghole M4 ISO14580 */
export const MountingHole_4_3mm_M4_ISO14580: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_ISO14580", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_ISO14580_Pad
 * Keywords: mountinghole M4 ISO14580 */
export const MountingHole_4_3mm_M4_ISO14580_Pad: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_ISO14580_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_ISO14580_Pad_TopBottom
 * Keywords: mountinghole M4 ISO14580 */
export const MountingHole_4_3mm_M4_ISO14580_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_ISO14580_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_ISO14580_Pad_TopOnly
 * Keywords: mountinghole M4 ISO14580 */
export const MountingHole_4_3mm_M4_ISO14580_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_ISO14580_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_ISO7380
 * Keywords: mountinghole M4 ISO7380 */
export const MountingHole_4_3mm_M4_ISO7380: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_ISO7380", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_ISO7380_Pad
 * Keywords: mountinghole M4 ISO7380 */
export const MountingHole_4_3mm_M4_ISO7380_Pad: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_ISO7380_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_ISO7380_Pad_TopBottom
 * Keywords: mountinghole M4 ISO7380 */
export const MountingHole_4_3mm_M4_ISO7380_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_ISO7380_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_ISO7380_Pad_TopOnly
 * Keywords: mountinghole M4 ISO7380 */
export const MountingHole_4_3mm_M4_ISO7380_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_ISO7380_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_Pad
 * Keywords: mountinghole M4 */
export const MountingHole_4_3mm_M4_Pad: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_Pad_TopBottom
 * Keywords: mountinghole M4 */
export const MountingHole_4_3mm_M4_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_Pad_TopOnly
 * Keywords: mountinghole M4 */
export const MountingHole_4_3mm_M4_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3mm, M4, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.3mm_M4_Pad_Via
 * Keywords: mountinghole M4 */
export const MountingHole_4_3mm_M4_Pad_Via: Footprint = { id: "MountingHole:MountingHole_4.3mm_M4_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3x6.2mm, M4
 * KiCad: MountingHole:MountingHole_4.3x6.2mm_M4_Pad
 * Keywords: mounting hole 4.3x6.2mm m4 */
export const MountingHole_4_3x6_2mm_M4_Pad: Footprint = { id: "MountingHole:MountingHole_4.3x6.2mm_M4_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.3x6.2mm, M4
 * KiCad: MountingHole:MountingHole_4.3x6.2mm_M4_Pad_Via
 * Keywords: mounting hole 4.3x6.2mm m4 */
export const MountingHole_4_3x6_2mm_M4_Pad_Via: Footprint = { id: "MountingHole:MountingHole_4.3x6.2mm_M4_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.5mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.5mm
 * Keywords: mountinghole */
export const MountingHole_4_5mm: Footprint = { id: "MountingHole:MountingHole_4.5mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 4.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.5mm_Pad
 * Keywords: mountinghole */
export const MountingHole_4_5mm_Pad: Footprint = { id: "MountingHole:MountingHole_4.5mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.5mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_4_5mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_4.5mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.5mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_4_5mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_4.5mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4.5mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_4_5mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_4.5mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4mm
 * Keywords: mountinghole */
export const MountingHole_4mm: Footprint = { id: "MountingHole:MountingHole_4mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 4mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4mm_Pad
 * Keywords: mountinghole */
export const MountingHole_4mm_Pad: Footprint = { id: "MountingHole:MountingHole_4mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_4mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_4mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_4mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_4mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 4mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_4mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_4mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_4mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5
 * Keywords: mountinghole M5 */
export const MountingHole_5_3mm_M5: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 5.3mm, M5, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_DIN965
 * Keywords: mountinghole M5 DIN965 */
export const MountingHole_5_3mm_M5_DIN965: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_DIN965", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_DIN965_Pad
 * Keywords: mountinghole M5 DIN965 */
export const MountingHole_5_3mm_M5_DIN965_Pad: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_DIN965_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_DIN965_Pad_TopBottom
 * Keywords: mountinghole M5 DIN965 */
export const MountingHole_5_3mm_M5_DIN965_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_DIN965_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_DIN965_Pad_TopOnly
 * Keywords: mountinghole M5 DIN965 */
export const MountingHole_5_3mm_M5_DIN965_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_DIN965_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_ISO14580
 * Keywords: mountinghole M5 ISO14580 */
export const MountingHole_5_3mm_M5_ISO14580: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_ISO14580", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_ISO14580_Pad
 * Keywords: mountinghole M5 ISO14580 */
export const MountingHole_5_3mm_M5_ISO14580_Pad: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_ISO14580_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_ISO14580_Pad_TopBottom
 * Keywords: mountinghole M5 ISO14580 */
export const MountingHole_5_3mm_M5_ISO14580_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_ISO14580_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_ISO14580_Pad_TopOnly
 * Keywords: mountinghole M5 ISO14580 */
export const MountingHole_5_3mm_M5_ISO14580_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_ISO14580_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_ISO7380
 * Keywords: mountinghole M5 ISO7380 */
export const MountingHole_5_3mm_M5_ISO7380: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_ISO7380", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_ISO7380_Pad
 * Keywords: mountinghole M5 ISO7380 */
export const MountingHole_5_3mm_M5_ISO7380_Pad: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_ISO7380_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_ISO7380_Pad_TopBottom
 * Keywords: mountinghole M5 ISO7380 */
export const MountingHole_5_3mm_M5_ISO7380_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_ISO7380_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_ISO7380_Pad_TopOnly
 * Keywords: mountinghole M5 ISO7380 */
export const MountingHole_5_3mm_M5_ISO7380_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_ISO7380_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_Pad
 * Keywords: mountinghole M5 */
export const MountingHole_5_3mm_M5_Pad: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_Pad_TopBottom
 * Keywords: mountinghole M5 */
export const MountingHole_5_3mm_M5_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_Pad_TopOnly
 * Keywords: mountinghole M5 */
export const MountingHole_5_3mm_M5_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.3mm, M5, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.3mm_M5_Pad_Via
 * Keywords: mountinghole M5 */
export const MountingHole_5_3mm_M5_Pad_Via: Footprint = { id: "MountingHole:MountingHole_5.3mm_M5_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.5mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.5mm
 * Keywords: mountinghole */
export const MountingHole_5_5mm: Footprint = { id: "MountingHole:MountingHole_5.5mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 5.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.5mm_Pad
 * Keywords: mountinghole */
export const MountingHole_5_5mm_Pad: Footprint = { id: "MountingHole:MountingHole_5.5mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.5mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_5_5mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_5.5mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.5mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_5_5mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_5.5mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5.5mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_5_5mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_5.5mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5mm
 * Keywords: mountinghole */
export const MountingHole_5mm: Footprint = { id: "MountingHole:MountingHole_5mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5mm_Pad
 * Keywords: mountinghole */
export const MountingHole_5mm_Pad: Footprint = { id: "MountingHole:MountingHole_5mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_5mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_5mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_5mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_5mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_5mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_5mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_5mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6
 * Keywords: mountinghole M6 */
export const MountingHole_6_4mm_M6: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 6.4mm, M6, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_DIN965
 * Keywords: mountinghole M6 DIN965 */
export const MountingHole_6_4mm_M6_DIN965: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_DIN965", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_DIN965_Pad
 * Keywords: mountinghole M6 DIN965 */
export const MountingHole_6_4mm_M6_DIN965_Pad: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_DIN965_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_DIN965_Pad_TopBottom
 * Keywords: mountinghole M6 DIN965 */
export const MountingHole_6_4mm_M6_DIN965_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_DIN965_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_DIN965_Pad_TopOnly
 * Keywords: mountinghole M6 DIN965 */
export const MountingHole_6_4mm_M6_DIN965_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_DIN965_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_ISO14580
 * Keywords: mountinghole M6 ISO14580 */
export const MountingHole_6_4mm_M6_ISO14580: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_ISO14580", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_ISO14580_Pad
 * Keywords: mountinghole M6 ISO14580 */
export const MountingHole_6_4mm_M6_ISO14580_Pad: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_ISO14580_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_ISO14580_Pad_TopBottom
 * Keywords: mountinghole M6 ISO14580 */
export const MountingHole_6_4mm_M6_ISO14580_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_ISO14580_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_ISO14580_Pad_TopOnly
 * Keywords: mountinghole M6 ISO14580 */
export const MountingHole_6_4mm_M6_ISO14580_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_ISO14580_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_ISO7380
 * Keywords: mountinghole M6 ISO7380 */
export const MountingHole_6_4mm_M6_ISO7380: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_ISO7380", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_ISO7380_Pad
 * Keywords: mountinghole M6 ISO7380 */
export const MountingHole_6_4mm_M6_ISO7380_Pad: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_ISO7380_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_ISO7380_Pad_TopBottom
 * Keywords: mountinghole M6 ISO7380 */
export const MountingHole_6_4mm_M6_ISO7380_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_ISO7380_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_ISO7380_Pad_TopOnly
 * Keywords: mountinghole M6 ISO7380 */
export const MountingHole_6_4mm_M6_ISO7380_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_ISO7380_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_Pad
 * Keywords: mountinghole M6 */
export const MountingHole_6_4mm_M6_Pad: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_Pad_TopBottom
 * Keywords: mountinghole M6 */
export const MountingHole_6_4mm_M6_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_Pad_TopOnly
 * Keywords: mountinghole M6 */
export const MountingHole_6_4mm_M6_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.4mm, M6, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.4mm_M6_Pad_Via
 * Keywords: mountinghole M6 */
export const MountingHole_6_4mm_M6_Pad_Via: Footprint = { id: "MountingHole:MountingHole_6.4mm_M6_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.5mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.5mm
 * Keywords: mountinghole */
export const MountingHole_6_5mm: Footprint = { id: "MountingHole:MountingHole_6.5mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 6.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.5mm_Pad
 * Keywords: mountinghole */
export const MountingHole_6_5mm_Pad: Footprint = { id: "MountingHole:MountingHole_6.5mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.5mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_6_5mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_6.5mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.5mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_6_5mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_6.5mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6.5mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6.5mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_6_5mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_6.5mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6mm, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6mm
 * Keywords: mountinghole */
export const MountingHole_6mm: Footprint = { id: "MountingHole:MountingHole_6mm", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 6mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6mm_Pad
 * Keywords: mountinghole */
export const MountingHole_6mm_Pad: Footprint = { id: "MountingHole:MountingHole_6mm_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6mm_Pad_TopBottom
 * Keywords: mountinghole */
export const MountingHole_6mm_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_6mm_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6mm_Pad_TopOnly
 * Keywords: mountinghole */
export const MountingHole_6mm_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_6mm_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 6mm, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_6mm_Pad_Via
 * Keywords: mountinghole */
export const MountingHole_6mm_Pad_Via: Footprint = { id: "MountingHole:MountingHole_6mm_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 8.4mm, M8, no annular, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_8.4mm_M8
 * Keywords: mountinghole M8 */
export const MountingHole_8_4mm_M8: Footprint = { id: "MountingHole:MountingHole_8.4mm_M8", ...{"pads":[],"mounting":"other"} }

/** Mounting Hole 8.4mm, M8, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_8.4mm_M8_Pad
 * Keywords: mountinghole M8 */
export const MountingHole_8_4mm_M8_Pad: Footprint = { id: "MountingHole:MountingHole_8.4mm_M8_Pad", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 8.4mm, M8, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_8.4mm_M8_Pad_TopBottom
 * Keywords: mountinghole M8 */
export const MountingHole_8_4mm_M8_Pad_TopBottom: Footprint = { id: "MountingHole:MountingHole_8.4mm_M8_Pad_TopBottom", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 8.4mm, M8, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_8.4mm_M8_Pad_TopOnly
 * Keywords: mountinghole M8 */
export const MountingHole_8_4mm_M8_Pad_TopOnly: Footprint = { id: "MountingHole:MountingHole_8.4mm_M8_Pad_TopOnly", ...{"pads":["1"],"mounting":"through_hole"} }

/** Mounting Hole 8.4mm, M8, generated by kicad-footprint-generator mountinghole.py
 * KiCad: MountingHole:MountingHole_8.4mm_M8_Pad_Via
 * Keywords: mountinghole M8 */
export const MountingHole_8_4mm_M8_Pad_Via: Footprint = { id: "MountingHole:MountingHole_8.4mm_M8_Pad_Via", ...{"pads":["1"],"mounting":"through_hole"} }

/** Tooling Hole 1.152mm, 1.3mm solder mask, JLCPCB specification, https://jlcpcb.com/help/article/How-to-add-tooling-holes-for-PCB-assembly-order
 * KiCad: MountingHole:ToolingHole_1.152mm
 * Keywords: mounting */
export const ToolingHole_1_152mm: Footprint = { id: "MountingHole:ToolingHole_1.152mm", ...{"pads":[],"mounting":"other"} }
