// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** KiCad: C5354889:CONN-TH_4P-P3.00_212528-0400 */
export const CONN_TH_4P_P3_00_212528_0400: Footprint = { id: "C5354889:CONN-TH_4P-P3.00_212528-0400", file: fileURLToPath(new URL("./CONN-TH_4P-P3.00_212528-0400.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["1","2","3","4"],"mounting":"through_hole"} }
