// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * 212528-0400
 *
 * KiCad symbol: `C5354889:212528-0400`. Reference prefix: `CN`.
 * @see https://www.lcsc.com/datasheet/C5354889.pdf
 * Default footprint: C5354889:CONN-TH_4P-P3.00_212528-0400.
 */
export class _212528_0400 extends Component.withPins({
  "P4": "4",
  "P3": "3",
  "P2": "2",
  "P1": "1",
}) {
  override symbolSource = fileURLToPath(new URL("./C5354889.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { P4: "passive", P3: "passive", P2: "passive", P1: "passive", ...opts.pinTypes } });
  }
  override schema = "C5354889:212528-0400";
  override referencePrefix = "CN";
}
