// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** KiCad: C2969868:SOD-123FL_L2.6-W1.6-LS3.5-FD */
export const SOD_123FL_L2_6_W1_6_LS3_5_FD: Footprint = { id: "C2969868:SOD-123FL_L2.6-W1.6-LS3.5-FD", file: fileURLToPath(new URL("./SOD-123FL_L2.6-W1.6-LS3.5-FD.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["1","2"],"mounting":"smd"} }
