// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * STPS2H100ZFY
 *
 * KiCad symbol: `C2969868:STPS2H100ZFY`. Reference prefix: `U`.
 * @see https://www.lcsc.com/datasheet/C2969868.pdf
 * Keywords: Schottky Barrier Diodes (SBD).
 * Default footprint: C2969868:SOD-123FL_L2.6-W1.6-LS3.5-FD.
 */
export class STPS2H100ZFY extends Component.withPins({
  "A": "1",
  "C": "2",
}) {
  override symbolSource = fileURLToPath(new URL("./C2969868.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { A: "passive", C: "passive", ...opts.pinTypes } });
  }
  override schema = "C2969868:STPS2H100ZFY";
  override referencePrefix = "U";
}
