// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** KiCad: C134364:SOT-363_L2.0-W1.3-P0.65-LS2.1-BR */
export const SOT_363_L2_0_W1_3_P0_65_LS2_1_BR: Footprint = { id: "C134364:SOT-363_L2.0-W1.3-P0.65-LS2.1-BR", file: fileURLToPath(new URL("./SOT-363_L2.0-W1.3-P0.65-LS2.1-BR.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["1","2","3","4","5","6"],"mounting":"smd"} }
