// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * BAS40DW-04-7-F
 *
 * KiCad symbol: `C134364:BAS40DW-04-7-F`. Reference prefix: `D`.
 * @see https://lcsc.com/product-detail/Schottky-Barrier-Diodes-SBD_DIODES_BAS40DW-04-7-F_BAS40DW-04-7-F_C134364.html
 * Keywords: Schottky Barrier Diodes (SBD).
 * Default footprint: C134364:SOT-363_L2.0-W1.3-P0.65-LS2.1-BR.
 */
export class BAS40DW_04_7_F extends Component.withPins({
  "A1": "1",
  "C1": "2",
  "AC2": "3",
  "A2": "4",
  "C2": "5",
  "AC1": "6",
}) {
  override symbolSource = fileURLToPath(new URL("./C134364.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { A1: "passive", C1: "passive", AC2: "passive", A2: "passive", C2: "passive", AC1: "passive", ...opts.pinTypes } });
  }
  override schema = "C134364:BAS40DW-04-7-F";
  override referencePrefix = "D";
}
