// Generated from KiCad symbols by export_components.ts.
import { Component } from "ts-kicad";

/**
 * Motorola M*CORE  upro 100 pins
 *
 * KiCad symbol: `MCU_NXP_MCore:MMC2114CFCPU`. Reference prefix: `U`.
 * @see https://www.nxp.com/docs/en/data-sheet/MMC2114.pdf
 */
export class MMC2114CFCPU extends Component.withPins({
  "PA6": "1",
  "PA5": "2",
  "PA4": "3",
  "PA3": "4",
  "PA2": "5",
  "PA1": "6",
  "PA0": "7",
  "PB7": "8",
  "PB6": "9",
  "PB5": "10",
  "PB4": "11",
  "VSS_12": "12",
  "VDD_13": "13",
  "PB3": "14",
  "PB2": "15",
  "PB1": "16",
  "PB0": "17",
  "PC7": "18",
  "PC6": "19",
  "PC5": "20",
  "VSS_21": "21",
  "VDD_22": "22",
  "PC4": "23",
  "PC3": "24",
  "PC2": "25",
  "PC1": "26",
  "PC0": "27",
  "PD7": "28",
  "PD6": "29",
  "PD5": "30",
  "PD4": "31",
  "PD3": "32",
  "PD2": "33",
  "PD1": "34",
  "PD0": "35",
  "ICOC23": "36",
  "ICOC22": "37",
  "ICOC21": "38",
  "ICOC20": "39",
  "ICOC13": "40",
  "ICOC12": "41",
  "IC0C11": "42",
  "ICOC10": "43",
  "TEST": "44",
  "TXD2": "45",
  "RXD2": "46",
  "TXD1": "47",
  "RXD1": "48",
  "INT0": "49",
  "INT1": "50",
  "VSSF": "51",
  "VDDF": "52",
  "INT2": "53",
  "VSS_54": "54",
  "VDD_55": "55",
  "INT3": "56",
  "INT4": "57",
  "INT5": "58",
  "INT6": "60",
  "INT7": "61",
  "MOSI": "62",
  "MISO": "63",
  "VSTBY": "64",
  "SCK": "65",
  "SS": "66",
  "PE7": "67",
  "PE6": "68",
  "PE5": "69",
  "VDDH": "70",
  "PQB3": "71",
  "PQB2": "72",
  "PQB1": "73",
  "PQB0": "74",
  "PQA4": "75",
  "PQA3": "76",
  "PQA1": "77",
  "PQA0": "78",
  "VrL": "79",
  "VrH": "80",
  "VSSA": "81",
  "VDDA": "82",
  "RESET": "83",
  "RSTOUT": "84",
  "PLLEN": "85",
  "XTAL": "86",
  "EXTAL": "87",
  "VSS_88": "88",
  "VSS_89": "89",
  "CLKOUT": "90",
  "VDD_91": "91",
  "TCLK": "92",
  "TDI": "93",
  "TDO": "94",
  "TMS": "95",
  "VSS_96": "96",
  "VDD_97": "97",
  "TRST": "98",
  "DE": "99",
  "PA7": "100",
}) {
  constructor(refOrOpts: string | ConstructorParameters<typeof Component>[0] = {}, options: ConstructorParameters<typeof Component>[0] = {}) {
    const opts = typeof refOrOpts === 'string' ? { ...options, ref: refOrOpts } : refOrOpts;
    super({ ...opts, pinTypes: { PA6: "bidirectional", PA5: "bidirectional", PA4: "bidirectional", PA3: "bidirectional", PA2: "bidirectional", PA1: "bidirectional", PA0: "bidirectional", PB7: "bidirectional", PB6: "bidirectional", PB5: "bidirectional", PB4: "bidirectional", VSS_12: "power_in", VDD_13: "power_in", PB3: "bidirectional", PB2: "bidirectional", PB1: "bidirectional", PB0: "bidirectional", PC7: "bidirectional", PC6: "bidirectional", PC5: "bidirectional", VSS_21: "power_in", VDD_22: "power_in", PC4: "bidirectional", PC3: "bidirectional", PC2: "bidirectional", PC1: "bidirectional", PC0: "bidirectional", PD7: "bidirectional", PD6: "bidirectional", PD5: "bidirectional", PD4: "bidirectional", PD3: "bidirectional", PD2: "bidirectional", PD1: "bidirectional", PD0: "bidirectional", ICOC23: "bidirectional", ICOC22: "bidirectional", ICOC21: "bidirectional", ICOC20: "bidirectional", ICOC13: "bidirectional", ICOC12: "bidirectional", IC0C11: "bidirectional", ICOC10: "bidirectional", TEST: "bidirectional", TXD2: "bidirectional", RXD2: "bidirectional", TXD1: "bidirectional", RXD1: "bidirectional", INT0: "bidirectional", INT1: "bidirectional", VSSF: "power_in", VDDF: "power_in", INT2: "bidirectional", VSS_54: "power_in", VDD_55: "power_in", INT3: "bidirectional", INT4: "bidirectional", INT5: "bidirectional", INT6: "bidirectional", INT7: "bidirectional", MOSI: "bidirectional", MISO: "bidirectional", VSTBY: "power_in", SCK: "bidirectional", SS: "bidirectional", PE7: "bidirectional", PE6: "bidirectional", PE5: "bidirectional", VDDH: "power_in", PQB3: "bidirectional", PQB2: "bidirectional", PQB1: "bidirectional", PQB0: "bidirectional", PQA4: "bidirectional", PQA3: "bidirectional", PQA1: "bidirectional", PQA0: "bidirectional", VrL: "input", VrH: "input", VSSA: "power_in", VDDA: "power_in", RESET: "input", RSTOUT: "output", PLLEN: "input", XTAL: "output", EXTAL: "input", VSS_88: "power_in", VSS_89: "power_in", CLKOUT: "output", VDD_91: "power_in", TCLK: "input", TDI: "input", TDO: "output", TMS: "input", VSS_96: "power_in", VDD_97: "power_in", TRST: "input", DE: "output", PA7: "bidirectional", ...opts.pinTypes } });
  }
  override schema = "MCU_NXP_MCore:MMC2114CFCPU";
  override referencePrefix = "U";
}
