// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** 1KΩ (1001) ±1%
   * KiCad: C21190:R0603 */
export const R0603: Footprint = { id: "C21190:R0603", file: fileURLToPath(new URL("./R0603.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["1","2"],"mounting":"smd"} }
