// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * 0603WAF1001T5E
 *
 * KiCad symbol: `C21190:0603WAF1001T5E`. Reference prefix: `R`.
 * @see https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_1KR-1001-1_C21190.html
 * Keywords: Resistors.
 * Default footprint: C21190:R0603.
 */
export class _0603WAF1001T5E extends Component.withPins({
  "P2": "2",
  "P1": "1",
}) {
  override symbolSource = fileURLToPath(new URL("./C21190.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { P2: "input", P1: "input", ...opts.pinTypes } });
  }
  override schema = "C21190:0603WAF1001T5E";
  override referencePrefix = "R";
}
