// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** KiCad: C293583:CONN-TH_5018761840 */
export const CONN_TH_5018761840: Footprint = { id: "C293583:CONN-TH_5018761840", file: fileURLToPath(new URL("./CONN-TH_5018761840.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["1","10","11","12","13","14","15","16","17","18","2","3","4","5","6","7","8","9"],"mounting":"through_hole"} }
