// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * 5018761840
 *
 * KiCad symbol: `C293583:5018761840`. Reference prefix: `U`.
 * @see https://lcsc.com/product-detail/PCB-Connectors-Headers-Male-Pins_MOLEX-5018761840_C293583.html
 * Keywords: Wire To Board / Wire To Wire Connector.
 * Default footprint: C293583:CONN-TH_5018761840.
 */
export class _5018761840 extends Component.withPins({
  "P1": "1",
  "P2": "2",
  "P3": "3",
  "P4": "4",
  "P5": "5",
  "P6": "6",
  "P7": "7",
  "P8": "8",
  "P9": "9",
  "P10": "10",
  "P11": "11",
  "P12": "12",
  "P13": "13",
  "P14": "14",
  "P15": "15",
  "P16": "16",
  "P17": "17",
  "P18": "18",
}) {
  override symbolSource = fileURLToPath(new URL("./C293583.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { P1: "passive", P2: "passive", P3: "passive", P4: "passive", P5: "passive", P6: "passive", P7: "passive", P8: "passive", P9: "passive", P10: "passive", P11: "passive", P12: "passive", P13: "passive", P14: "passive", P15: "passive", P16: "passive", P17: "passive", P18: "passive", ...opts.pinTypes } });
  }
  override schema = "C293583:5018761840";
  override referencePrefix = "U";
}
