// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** KiCad: C129018:USB-C-SMD_TYPE-C-USB-20 */
export const USB_C_SMD_TYPE_C_USB_20: Footprint = { id: "C129018:USB-C-SMD_TYPE-C-USB-20", file: fileURLToPath(new URL("./USB-C-SMD_TYPE-C-USB-20.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["0","A1","A10","A11","A12","A2","A3","A4","A5","A6","A7","A8","A9","B1","B10","B11","B12","B2","B3","B4","B5","B6","B7","B8","B9"],"mounting":"mixed"} }
