// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * TYPE-C-31-M-04
 *
 * KiCad symbol: `C129018:TYPE-C-31-M-04`. Reference prefix: `USBC`.
 * @see https://lcsc.com/product-detail/USB-Type-C_Korean-Hroparts-Elec-TYPE-C-31-M-04_C129018.html
 * Keywords: USB Connectors.
 * Default footprint: C129018:USB-C-SMD_TYPE-C-USB-20.
 */
export class TYPE_C_31_M_04 extends Component.withPins({
  "GND_B1": "B1",
  "SSTXp2": "B2",
  "SSTXn2": "B3",
  "VBUS_B4": "B4",
  "CC2": "B5",
  "DP2": "B6",
  "DN2": "B7",
  "SUB2": "B8",
  "VBUS_B9": "B9",
  "SSRXn1": "B10",
  "SSRXp1": "B11",
  "GND_B12": "B12",
  "P0": "0",
  "GND_A1": "A1",
  "SSTXP1": "A2",
  "SSTXn1": "A3",
  "VBUS_A4": "A4",
  "CC1": "A5",
  "DP1": "A6",
  "DN1": "A7",
  "SUB1": "A8",
  "VBUS_A9": "A9",
  "SSRXn2": "A10",
  "SSRXp2": "A11",
  "GND_A12": "A12",
}) {
  override symbolSource = fileURLToPath(new URL("./C129018.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { GND_B1: "unspecified", SSTXp2: "unspecified", SSTXn2: "unspecified", VBUS_B4: "unspecified", CC2: "unspecified", DP2: "unspecified", DN2: "unspecified", SUB2: "unspecified", VBUS_B9: "unspecified", SSRXn1: "unspecified", SSRXp1: "unspecified", GND_B12: "unspecified", P0: "unspecified", GND_A1: "unspecified", SSTXP1: "unspecified", SSTXn1: "unspecified", VBUS_A4: "unspecified", CC1: "unspecified", DP1: "unspecified", DN1: "unspecified", SUB1: "unspecified", VBUS_A9: "unspecified", SSRXn2: "unspecified", SSRXp2: "unspecified", GND_A12: "unspecified", ...opts.pinTypes } });
  }
  override schema = "C129018:TYPE-C-31-M-04";
  override referencePrefix = "USBC";
}
