import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, relative, resolve } from 'node:path'
import { renderComponents, identifier } from './export_components'
import { libraryXml } from './internal-symbols'
import { readSymbolLibrary } from './symbol_library'
import { footprintMetadata } from './internal-footprints'
import { normalizeFootprint } from './normalize_footprint'
import { parse, dump, child, children, val, node, atom } from './kicad_sexpr'

const managed = 'Managed by ts-kicad convert'
const header = '// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.\n'
const modelExtension = /\.(step|stp|wrl)$/i
const q = JSON.stringify
const urlPath = (from:string,to:string) => './'+relative(from,to).split('/').map(encodeURIComponent).join('/')
function filesIn(directory: string): string[] {
  return readdirSync(directory,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(entry => {
    const path=join(directory,entry.name)
    if(entry.isSymbolicLink())throw new Error('Symlinks are not supported in native libraries: '+path)
    return entry.isDirectory()?filesIn(path):[path]
  })
}

/** Separate symbol and footprint bindings beside each package's native assets. */
export function convertLibraries(projectDirectory: string, folders: readonly string[] = []) {
  const project=resolve(projectDirectory),input=join(project,'lib')
  const selected=new Set(folders)
  for(const folder of selected)if(!folder||folder==='.'||folder==='..'||/[\\/]/.test(folder))throw new Error('Expected folder names inside lib')
  if(!existsSync(input))throw new Error('Library directory not found: '+input)
  const packages=readdirSync(input,{withFileTypes:true}).filter(entry=>!selected.size||selected.has(entry.name)).sort((a,b)=>a.name.localeCompare(b.name))
  for(const folder of selected)if(!packages.some(entry=>entry.name===folder&&entry.isDirectory()))throw new Error('Library folder not found: '+folder)
  const files=selected.size?packages.flatMap(entry=>filesIn(join(input,entry.name))):filesIn(input),models=files.filter(file=>modelExtension.test(file)),byBasename=new Map<string,string[]>()
  for(const file of models)byBasename.set(basename(file),[...byBasename.get(basename(file))??[],file])
  const edits=new Map<string,{before:string|undefined;after:string|undefined}>()
  const edit=(path:string,after:string|undefined)=>{const before=existsSync(path)?readFileSync(path,'utf8'):undefined;if(before!==after)edits.set(path,{before,after})}
  const symbolLibraries=new Map<string,string>(),footprintLibraries=new Map<string,string>()
  let symbols=0,footprints=0
  for(const entry of packages){
    if(!entry.isDirectory()){
      if(/\.(kicad_sym|kicad_mod|step|stp|wrl)$/i.test(entry.name))throw new Error('Put native files in lib/<package-name>/: '+entry.name)
      continue
    }
    const directory=join(input,entry.name),packageFiles=files.filter(file=>file.startsWith(directory+'/'))
    for(const file of ['symbols.ts','footprints.ts']){const output=join(directory,file);if(existsSync(output)&&!readFileSync(output,'utf8').startsWith('// Generated by ts-kicad convert.'))throw new Error('Refusing to overwrite non-generated file: '+output)}
    const names=new Set<string>(),footprintNames=new Set<string>()
    let text=header+"import { Component } from 'ts-kicad'\nimport { fileURLToPath } from 'node:url'\n\n",footprintText=header+"import type { Footprint } from 'ts-kicad'\nimport { fileURLToPath } from 'node:url'\n\n"
    for(const file of packageFiles.filter(file=>file.endsWith('.kicad_sym'))){
      const library=basename(file,'.kicad_sym')
      if(symbolLibraries.has(library))throw new Error('Duplicate symbol library name: '+library)
      symbolLibraries.set(library,file)
      const definitions=readSymbolLibrary(file),rendered=renderComponents(libraryXml(library,definitions),{symbolSource:urlPath(directory,file)})
      for(const part of Object.values(rendered.libraries)){if(names.has(part.className))throw new Error('Duplicate symbol TypeScript name: '+part.className);names.add(part.className)}
      text+=rendered.text.replace(/^\/\/ Generated[^\n]*\n/,'').replace(/^import[^\n]*\n/gm,'').trim()+'\n\n'
      symbols+=definitions.size
    }
    for(const file of packageFiles.filter(file=>file.endsWith('.kicad_mod'))){
      const library=basename(dirname(file),'.pretty'),name=basename(file,'.kicad_mod'),id=library+':'+name,exported=identifier(name)
      const existing=footprintLibraries.get(library)
      if(existing&&existing!==dirname(file))throw new Error('Duplicate footprint library name: '+library)
      footprintLibraries.set(library,dirname(file))
      if(footprintNames.has(exported))throw new Error('Duplicate footprint or TypeScript name: '+id)
      footprintNames.add(exported)
      const originalText=readFileSync(file,'utf8'),tree=parse(originalText)
      if(!['footprint','module'].includes(val(tree[0])))throw new Error('Not a KiCad footprint: '+file)
      const replacements=new Map<string,string>()
      for(const model of children(tree,'model')){
        const original=val(model[1]),portable=original.replaceAll('\\','/')
        const candidates=[resolve(dirname(file),portable),resolve(project,portable.replace(/^\$\{KIPRJMOD\}\//,''))]
        let source=candidates.find(candidate=>models.includes(candidate))
        if(!source){
          const packageMatches=(byBasename.get(basename(portable))??[]).filter(file=>file.startsWith(directory+'/'))
          const matches=packageMatches.length?packageMatches:byBasename.get(basename(portable))??[]
          if(matches.length>1)throw new Error('Ambiguous 3D model '+original+' in '+file)
          source=matches[0]
        }
        if(source)replacements.set(original,'${KIPRJMOD}/'+relative(project,source))
        else if(!/^\$\{KICAD\d*_3DMODEL_DIR\}/.test(portable))console.warn('Warning: missing 3D model '+original+' referenced by '+id)
      }
      let normalized=originalText.replace(/(\(model\s+)("(?:\\.|[^"\\])*")/g,(_all,prefix,quoted)=>prefix+q(replacements.get(JSON.parse(quoted))??JSON.parse(quoted)))
      // A footprint saved from a board may carry placement angles and net assignments.
      normalized=normalizeFootprint(normalized)
      edit(file,normalized)
      const description=val(child(tree,'descr')[1]),tags=val(child(tree,'tags')[1])
      const doc=[description,'KiCad: '+id,tags&&'Keywords: '+tags].filter(Boolean).join('\n   * ').replace(/\*\//g,'* /')
      footprintText+='/** '+doc+' */\nexport const '+exported+': Footprint = { id: '+q(id)+', file: fileURLToPath(new URL('+q(urlPath(directory,file))+', import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...'+q(footprintMetadata(tree))+' }\n\n'
      footprints++
    }
    edit(join(directory,'symbols.ts'),text.replace(/[ \t]+$/gm,'').trimEnd()+'\n')
    edit(join(directory,'footprints.ts'),footprintText.replace(/[ \t]+$/gm,'').trimEnd()+'\n')
    const oldIndex=join(directory,'index.ts')
    if(existsSync(oldIndex)&&readFileSync(oldIndex,'utf8').startsWith('// Generated by ts-kicad convert.'))edit(oldIndex,undefined)
  }
  const table=(file:string,tag:string,libraries:Map<string,string>)=>{
    const path=join(project,file),tree=existsSync(path)?parse(readFileSync(path,'utf8')):node(tag,node('version',atom(7)))
    if(val(tree[0])!==tag)throw new Error('Invalid KiCad library table: '+path)
    const remaining=children(tree,'lib').filter(lib=>val(child(lib,'descr')[1])!==managed || (selected.size && ![...selected].some(folder=>val(child(lib,'uri')[1]).startsWith('${KIPRJMOD}/lib/'+folder+'/') || val(child(lib,'uri')[1])==='${KIPRJMOD}/lib/'+folder)))
    for(const [name,source]of libraries){
      const existing=remaining.find(lib=>val(child(lib,'name')[1])===name),uri='${KIPRJMOD}/'+relative(project,source)
      if(existing){if(val(child(existing,'uri')[1])!==uri)throw new Error('Library table name conflict: '+name);continue}
      remaining.push(node('lib',node('name',name),node('type','KiCad'),node('uri',uri),node('options',''),node('descr',managed)))
    }
    const result=tree.filter(value=>!Array.isArray(value)||val(value[0])!=='lib')
    result.push(...remaining);edit(path,dump(result)+'\n')
  }
  table('sym-lib-table','sym_lib_table',symbolLibraries)
  table('fp-lib-table','fp_lib_table',footprintLibraries)
  for(const file of files.filter(file=>/\.(zip|lib|kicad_sch)$/i.test(file)))console.warn('Warning: convert expects extracted .kicad_sym and .kicad_mod files; not importing '+relative(input,file))
  for(const [path,{before}]of edits)if((existsSync(path)?readFileSync(path,'utf8'):undefined)!==before)throw new Error('File changed during conversion: '+path)
  const applied:string[]=[]
  try {for(const [path,{after}]of edits){if(after===undefined)rmSync(path);else writeFileSync(path,after);applied.push(path)}}
  catch(error){for(const path of applied.reverse()){const before=edits.get(path)!.before;if(before===undefined)rmSync(path,{force:true});else writeFileSync(path,before)}throw error}
  console.log(`Converted ${symbols} symbols, ${footprints} footprints and ${models.length} models; generated symbols.ts and footprints.ts per lib/ package`)
  return {symbols,footprints,models:models.length}
}
export async function main(args:string[]){
  if(args.some(arg=>arg.startsWith('-')))throw new Error('Usage: ts-kicad convert [folder-name ...]')
  convertLibraries('.',args)
}
