// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import type { Footprint } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/** KiCad: C2673265:SO-8_L4.9-W3.9-P1.27-LS6.0-BL */
export const SO_8_L4_9_W3_9_P1_27_LS6_0_BL: Footprint = { id: "C2673265:SO-8_L4.9-W3.9-P1.27-LS6.0-BL", file: fileURLToPath(new URL("./SO-8_L4.9-W3.9-P1.27-LS6.0-BL.kicad_mod", import.meta.url)), projectDirectory: fileURLToPath(new URL("../../", import.meta.url)), ...{"pads":["1","2","3","4","5","6","7","8"],"mounting":"smd"} }
