// Generated by ts-kicad convert. Edit the native KiCad files, then convert again.
import { Component } from 'ts-kicad'
import { fileURLToPath } from 'node:url'

/**
 * DG419LEDY-T1-GE4
 *
 * KiCad symbol: `C2673265:DG419LEDY-T1-GE4`. Reference prefix: `U`.
 * @see https://www.lcsc.com/datasheet/C2673265.pdf
 * Keywords: Analog Switches / Multiplexers.
 * Default footprint: C2673265:SO-8_L4.9-W3.9-P1.27-LS6.0-BL.
 */
export class DG419LEDY_T1_GE4 extends Component.withPins({
  "COM": "1",
  "NC": "2",
  "GND": "3",
  "V+": "4",
  "VL": "5",
  "IN": "6",
  "V-": "7",
  "NO": "8",
}) {
  override symbolSource = fileURLToPath(new URL("./C2673265.kicad_sym", import.meta.url));
  constructor(opts: ConstructorParameters<typeof Component>[0] = {}) {
    super({ ...opts, pinTypes: { COM: "passive", NC: "passive", GND: "power_in", "V+": "power_in", VL: "power_in", IN: "input", "V-": "power_in", NO: "passive", ...opts.pinTypes } });
  }
  override schema = "C2673265:DG419LEDY-T1-GE4";
  override referencePrefix = "U";
}
